-- 1. Table for Users
CREATE TABLE IF NOT EXISTS users (
    username TEXT PRIMARY KEY,
    email TEXT UNIQUE,
    password TEXT NOT NULL,
    favorites JSONB DEFAULT '[]',
    genres JSONB DEFAULT '[]',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Table for Songs
CREATE TABLE IF NOT EXISTS songs (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    artist TEXT NOT NULL,
    url TEXT NOT NULL,
    cover TEXT,
    type TEXT DEFAULT 'audio',
    username TEXT REFERENCES users(username) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Table for Playlists
CREATE TABLE IF NOT EXISTS playlists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    username TEXT REFERENCES users(username) ON DELETE CASCADE,
    song_ids JSONB DEFAULT '[]',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Note: In a production app, you would enable RLS (Row Level Security).
-- For this personal project, we'll keep it simple, but you can enable it later.
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE songs ENABLE ROW LEVEL SECURITY;
ALTER TABLE playlists ENABLE ROW LEVEL SECURITY;

-- Simple policies to allow all access (since it's a personal app)
CREATE POLICY "Allow all access" ON users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access" ON songs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access" ON playlists FOR ALL USING (true) WITH CHECK (true);
